#!/bin/bash
cd "$(dirname "$0")"
rm -rf dist
mkdir dist

cd src
echo - Building CSS

cat css/popup.css css/main.css > ../dist/main_min.css

cp index.php ../dist/index.php
cp -r images ../dist/images
cp -r database ../dist/database


echo - Building Javascript
cat js/lib/extraFunctions.js js/lib/vector.js js/lib/popup.js js/server.js js/hitBoxManager.js js/components/component.js js/components/componentManager.js js/sideBar.js js/inputHandler.js js/popup.js js/renderer/drawLib.js js/renderer/camera.js js/renderer/renderer.js js/builder.js js/world.js js/app.js > ../dist/main_min.js


echo \|-------------------\|
echo \| Finished Building \|
echo \|-------------------\|
